"""Conservative Face Studio application package."""

from __future__ import annotations

import os

os.environ.setdefault("OPENCV_FORCE_DNN_ENGINE", "1")

from app.same_canvas_seed_support_policy import install_same_canvas_seed_support_policy
from app.same_canvas_seed_precision_policy import install_same_canvas_seed_precision_policy
from app.explicit_damage_domain_policy import install_explicit_damage_domain_policy
from app.multi_reference_runtime_policy import install_multi_reference_runtime_policy
from app.automatic_quality_policy import install_automatic_quality_policy
from app.observed_target_photometric_policy import install_observed_target_photometric_policy
from app.automatic_integrity_policy import install_automatic_integrity_policy
from app.pretrained_face_resilience_policy import install_pretrained_face_resilience_policy
from app.preflight_selective_deblur_policy import install_preflight_selective_deblur_policy
from app.severity_aware_deblur_policy import install_severity_aware_deblur_policy
from app.reference_guided_seed_policy import install_reference_guided_seed_policy
from app.fixed_primary_contract_policy import install_fixed_primary_contract_policy
from app.fixed_primary_policy import install_fixed_primary_policy
from app.cross_reference_preclean_autoinstall import install_cross_reference_preclean_autoinstall
from app.tiny_observed_evidence_autoinstall import install_tiny_observed_evidence_autoinstall
from app.full_residual_reconstruction_policy import install_full_residual_reconstruction_policy
from app.single_image_core_policy import install_single_image_core_policy
from app.evidence_confidence_runtime import install_evidence_confidence_runtime
from app.core_quality_gate_policy import install_core_quality_gate_policy

install_same_canvas_seed_support_policy()
install_same_canvas_seed_precision_policy()
install_explicit_damage_domain_policy()
install_multi_reference_runtime_policy()
install_automatic_quality_policy()
install_observed_target_photometric_policy()
install_automatic_integrity_policy()
install_pretrained_face_resilience_policy()
# First pass: protect reliable/occluded pixels. Second router: strong blur only.
install_preflight_selective_deblur_policy()
install_severity_aware_deblur_policy()
install_reference_guided_seed_policy()
install_fixed_primary_contract_policy()
install_fixed_primary_policy()
install_cross_reference_preclean_autoinstall()
install_tiny_observed_evidence_autoinstall()
install_full_residual_reconstruction_policy()
install_single_image_core_policy()
install_evidence_confidence_runtime()
install_core_quality_gate_policy()
